"""Central Section 6 MVP states, policies and stable error codes."""
from __future__ import annotations

AGENT_STATUS_RUNNING = "RUNNING"
AGENT_STATUS_WAITING_USER_INPUT = "WAITING_USER_INPUT"
AGENT_STATUS_WAITING_REVIEW = "WAITING_REVIEW"
AGENT_STATUS_COMPLETED = "COMPLETED"
AGENT_STATUS_COMPLETED_WITH_PENDING_REVIEW = "COMPLETED_WITH_PENDING_REVIEW"
AGENT_STATUS_FAILED = "FAILED"
AGENT_STATUS_MANUAL_INTERVENTION_REQUIRED = "MANUAL_INTERVENTION_REQUIRED"
AGENT_STATUS_DECISION_CONTEXT_RECONFIRMATION_REQUIRED = "DECISION_CONTEXT_RECONFIRMATION_REQUIRED"

DECISION_CONTEXT_STRICT_BLOCK = "STRICT_BLOCK"
DECISION_CONTEXT_PAUSE_DECISION_LAYER = "PAUSE_DECISION_LAYER"
DECISION_CONTEXT_POLICIES = {
    DECISION_CONTEXT_STRICT_BLOCK,
    DECISION_CONTEXT_PAUSE_DECISION_LAYER,
}
# Business has not selected the final semantics. Keep the existing strict behavior.
DEFAULT_DECISION_CONTEXT_POLICY = DECISION_CONTEXT_STRICT_BLOCK

DEFAULT_MAX_ROUNDS = 5

ERROR_DECISION_CONTEXT_RECONFIRMATION_REQUIRED = "DECISION_CONTEXT_RECONFIRMATION_REQUIRED"
ERROR_FACT_CANDIDATE_DUPLICATE = "FACT_CANDIDATE_DUPLICATE"
ERROR_FACT_CANDIDATE_INVALID = "FACT_CANDIDATE_INVALID"
ERROR_TASK_REQUIREMENTS_INVALID = "TASK_REQUIREMENTS_INVALID"
ERROR_UNSUPPORTED_REQUIREMENT_OPERATOR = "UNSUPPORTED_REQUIREMENT_OPERATOR"

# Enterprise evaluation stable error codes.
ERROR_EVALUATION_MODEL_INVALID = "EVALUATION_MODEL_INVALID"
ERROR_EVALUATION_MODEL_SELECTION_MISMATCH = "EVALUATION_MODEL_SELECTION_MISMATCH"
ERROR_EVALUATION_MODEL_CONTENT_CONFLICT = "EVALUATION_MODEL_CONTENT_CONFLICT"
ERROR_EVALUATION_WEIGHT_POLICY_CONFLICT = "EVALUATION_WEIGHT_POLICY_CONFLICT"
ERROR_EVALUATION_RULE_NOT_REGISTERED = "EVALUATION_RULE_NOT_REGISTERED"
ERROR_EVALUATION_FEATURE_MISSING = "EVALUATION_FEATURE_MISSING"
ERROR_EVALUATION_PROVIDER_NOT_CONFIGURED = "EVALUATION_PROVIDER_NOT_CONFIGURED"
ERROR_EVALUATION_API_CALL_FAILED = "EVALUATION_API_CALL_FAILED"
ERROR_EVALUATION_REVIEW_PENDING = "EVALUATION_REVIEW_PENDING"
ERROR_EVALUATION_PUBLICATION_POLICY_NOT_CONFIRMED = "EVALUATION_PUBLICATION_POLICY_NOT_CONFIRMED"
ERROR_EVALUATION_RUN_NOT_FOUND = "EVALUATION_RUN_NOT_FOUND"
ERROR_EVALUATION_RUN_NOT_RESUMABLE = "EVALUATION_RUN_NOT_RESUMABLE"
