"""Storage semantic contracts; business code never depends on local filesystem paths."""
from __future__ import annotations
from typing import Any, Protocol

class CompanyIdentityRepository(Protocol):
    def list_companies(self)->list[dict[str,Any]]: ...

class EnterpriseProfileRepository(Protocol):
    def ensure_initialized(self)->None: ...
    def read_company_context(self,company_id:str)->dict[str,Any]: ...
    def read_profile(self,company_id:str,profile_type:str)->dict[str,Any]|None: ...
    def write_profile(self,company_id:str,profile_type:str,profile:dict[str,Any],*,update_source:str,updated_fields:list[str]|None=None,actor:dict[str,Any]|None=None)->dict[str,Any]: ...
    def history(self,company_id:str)->dict[str,list[dict[str,Any]]]: ...
    def history_entry(self,company_id:str,layer:str,version:int)->dict[str,Any]: ...
    def current_bundle(self,company_id:str)->dict[str,Any]: ...
    def restore_current_bundle(self,company_id:str,bundle:dict[str,Any])->None: ...
    def save_fact_candidate(self,candidate:dict[str,Any])->None: ...
    def list_fact_candidates(self,*,company_id:str|None=None)->list[dict[str,Any]]: ...
    def save_review_task(self,task:dict[str,Any])->None: ...
    def read_review_task(self,task_id:str)->dict[str,Any]: ...
    def list_review_tasks(self,*,company_id:str|None=None)->list[dict[str,Any]]: ...

class RawEnterpriseDataRepository(Protocol):
    def save_raw_api_response(self,record:dict[str,Any])->dict[str,Any]: ...
    def get_raw_api_response(self,raw_response_ref:str)->dict[str,Any]: ...
    def save_api_call_record(self,record:dict[str,Any])->None: ...
    def list_api_call_records(self,*,run_id:str|None=None,company_id:str|None=None)->list[dict[str,Any]]: ...
    def find_valid_api_cache(self,cache_key:str,*,at_utc:str)->dict[str,Any]|None: ...

class EvaluationRepository(Protocol):
    def save_evaluation_run(self,run:dict[str,Any])->None: ...
    def get_evaluation_run(self,run_id:str)->dict[str,Any]: ...
    def list_evaluation_runs(self,*,company_id:str|None=None,limit:int=20)->list[dict[str,Any]]: ...
    def save_evaluation_profile(self,company_id:str,profile:dict[str,Any],*,run_id:str)->dict[str,Any]: ...
    def get_current_evaluation_profile(self,company_id:str)->dict[str,Any]|None: ...
    def get_evaluation_profile_version(self,company_id:str,version:int)->dict[str,Any]: ...
    def list_evaluation_profile_versions(self,company_id:str)->list[dict[str,Any]]: ...
    def save_evaluation_card(self,company_id:str,card:dict[str,Any],*,run_id:str)->None: ...
    def get_current_evaluation_card(self,company_id:str)->dict[str,Any]|None: ...
    def save_acquisition_plan(self,plan:dict[str,Any])->None: ...
    def get_acquisition_plan(self,plan_id:str)->dict[str,Any]: ...

class AgentCheckpointRepository(Protocol):
    def save_evaluation_checkpoint(self,run_id:str,state:dict[str,Any])->dict[str,Any]: ...
    def get_evaluation_checkpoint(self,run_id:str)->dict[str,Any]: ...

class ProfileRepository(CompanyIdentityRepository,EnterpriseProfileRepository,RawEnterpriseDataRepository,EvaluationRepository,AgentCheckpointRepository,Protocol):
    def save_run(self,run:dict[str,Any])->None: ...
    def read_run(self,run_id:str)->dict[str,Any]: ...
    def list_runs(self,*,company_id:str|None=None,limit:int=20)->list[dict[str,Any]]: ...
    def read_task_requirements(self,company_id:str)->dict[str,Any]|None: ...
    def save_task_requirements(self,company_id:str,value:dict[str,Any])->None: ...
    def read_gap_inventory(self,company_id:str)->dict[str,Any]|None: ...
    def save_gap_inventory(self,company_id:str,value:dict[str,Any])->None: ...
    def audit(self,event_type:str,payload:dict[str,Any])->None: ...
